"""Yoga pose library (curated beginner mat set).

Pose data, Sanskrit names and illustrations are from the open-source Yoga API
(github.com/alexcumplido/yoga-api, MIT). Images are served from its CDN and
load in the browser; breathing/alignment cues and flow metadata are our own.
"""

POSES = {
    'cat_cow': {'label': 'Cat', 'sanskrit': 'Marjaryasana', 'description': 'From box neutral shift some weight to the palms. The wrists, elbows and shoulders are in one line. The abdomen is pulled in and up with the spine arched in a strong Cobra spine. The crown of the head is towards the…', 'benefits': 'Relieves the spine and neck. Energizes the body.', 'cue': 'Flow between rounding (Cat, exhale) and arching (Cow, inhale). Move with your breath.', 'image': 'https://res.cloudinary.com/dko1be2jy/image/upload/fl_sanitize/v1676483075/yoga-api/7_a6aspg.png', 'category': 'warmup', 'per_side': False, 'hold': 40},
    'child': {'label': "Child's Pose", 'sanskrit': 'Balasana', 'description': 'From a kneeling position, the toes and knees are together with most of the weight of the body resting on the heels of the feet. The arms are extended back resting alongside the legs. The forehead rests softly onto the…', 'benefits': 'Gently stretches the hips, thighs, and ankles. Calms the brain and helps relieve stress and fatigue. Relieves back and neck pain when done with head and torso…', 'cue': 'Knees wide, hips to heels, forehead down. Breathe slowly into your back.', 'image': 'https://res.cloudinary.com/dko1be2jy/image/upload/fl_sanitize/v1676483079/yoga-api/10_wzpo85.png', 'category': 'warmup', 'per_side': False, 'hold': 40},
    'downdog': {'label': 'Downward-Facing Dog', 'sanskrit': 'Adho Mukha Svanasana', 'description': 'From downward_dog.html the legs are straight with the sits bones tilted up and reaching for the sky. The feet are flat with the heels firmly rooted. One palm is flat with the knuckles evenly pressed into the earth. The…', 'benefits': 'Calms the brain and helps relieve stress and mild depression. Energizes the body. Stretches the shoulders, neck, hamstrings, calves, arches, and hands.…', 'cue': 'Hands shoulder-width, hips up and back, soft knees. Long spine, easy neck.', 'image': 'https://res.cloudinary.com/dko1be2jy/image/upload/fl_sanitize/v1676483081/yoga-api/15_vkviqn.png', 'category': 'warmup', 'per_side': False, 'hold': 30},
    'forward_fold': {'label': 'Standing Forward Bend', 'sanskrit': 'Uttanasana', 'description': 'From a standing position, the body is folded over at the crease of the hip with the spine long. The neck is relaxed and the crown of the head is towards the earth. The feet are rooted into the earth with the toes…', 'benefits': 'Calms the brain and helps relieve stress and mild depression. Stimulates the liver and kidneys. Stretches the hamstrings, calves, and hips. Strengthens the…', 'cue': 'Hinge from the hips, soft knees, let the head hang. Inhale lengthen, exhale fold.', 'image': 'https://res.cloudinary.com/dko1be2jy/image/upload/fl_sanitize/v1676483093/yoga-api/38_yb3thk.png', 'category': 'standing', 'per_side': False, 'hold': 30},
    'low_lunge': {'label': 'Low Lunge', 'sanskrit': 'Anjaneyasana', 'description': 'The front knee is bent in a 90-degree angle directly above the ankle and the back knee is resting on the earth with the top of the back foot pressed firmly into the earth. The hips are squared and pressed forward. The…', 'benefits': 'Stretches the chest, lungs, neck, belly and groin (psoas). Strengthens the shoulders, arms and back muscles. Strengthens and stretches the thighs, calves and…', 'cue': 'Back knee down, front knee over ankle, sink the hips. Lift the chest.', 'image': 'https://res.cloudinary.com/dko1be2jy/image/upload/fl_sanitize/v1676483086/yoga-api/23_k2jccj.png', 'category': 'standing', 'per_side': True, 'hold': 30},
    'warrior1': {'label': 'Warrior One', 'sanskrit': 'Virabhadrasana One', 'description': 'From a standing position, the legs are in a wide stance with the feet aligned and flat on the earth. The back foot is in a 60-degree angle towards the front. The hips are squared. The inner thighs are rotated towards…', 'benefits': 'Stretches the chest, lungs, shoulders, neck, belly and groin (psoas). Strengthens the shoulders, arms and back muscles. Strengthens and stretches the thighs,…', 'cue': 'Front knee bent, back heel down, hips and chest forward, arms up.', 'image': 'https://res.cloudinary.com/dko1be2jy/image/upload/fl_sanitize/v1676483096/yoga-api/44_dqeayo.png', 'category': 'standing', 'per_side': True, 'hold': 30},
    'warrior2': {'label': 'Warrior Two', 'sanskrit': 'Virabhadrasana Two', 'description': 'From a standing position, the legs are separated into a wide stance. The front knee is bent in a 90-degree angle directly above the ankle. The back leg is extended and straight with the outside edge of the back foot…', 'benefits': 'Strengthens and stretches the legs and ankles. Stretches the groin, chest, lungs, and shoulders. Stimulates abdominal organs. Increases stamina. Relieves…', 'cue': 'Front knee over ankle, arms parallel to the floor, gaze over the front hand.', 'image': 'https://res.cloudinary.com/dko1be2jy/image/upload/fl_sanitize/v1676483096/yoga-api/45_ehimr1.png', 'category': 'standing', 'per_side': True, 'hold': 30},
    'triangle': {'label': 'Triangle', 'sanskrit': 'Trikonasana', 'description': 'From a standing position, the legs are straight and separated into a wide stance. The feet are aligned and flat on the earth with the back foot in a 60-degree angle towards the front. The inner thighs are rotated…', 'benefits': 'Stretches and strengthens the thighs, knees, and ankles. Stretches the hips, groin, hamstrings, calves, shoulders, chest, and spine. Stimulates the abdominal…', 'cue': 'Straight legs, reach long over the front leg, open the chest to the ceiling.', 'image': 'https://res.cloudinary.com/dko1be2jy/image/upload/fl_sanitize/v1676483096/yoga-api/42_jawxqw.png', 'category': 'standing', 'per_side': True, 'hold': 30},
    'chair': {'label': 'Chair', 'sanskrit': 'Utkatasana', 'description': 'From a standing position, the feet are together and rooted into the earth with toes actively lifted. The knees are bent and the weight of the body is on the heels of the feet. The pelvis is tucked in and the ribcage is…', 'benefits': 'Strengthens the ankles, thighs, calves, and spine. Stretches shoulders and chest. Stimulates the abdominal organs, diaphragm, and heart. Reduces flat feet.…', 'cue': 'Sit the hips back as if into a chair, weight in the heels, arms reaching up.', 'image': 'https://res.cloudinary.com/dko1be2jy/image/upload/fl_sanitize/v1676483078/yoga-api/9_ewvoun.png', 'category': 'standing', 'per_side': False, 'hold': 25},
    'tree': {'label': 'Tree', 'sanskrit': 'Vrksasana', 'description': 'From a standing position, one foot is rooted into the earth with the opposite heel rooted into the inner thigh with the toes pointing towards the earth. The pelvis and the chin are tucked in. The arms are lifted above…', 'benefits': 'Strengthens the legs, ankles, and feet. Improves flexibility in the hips and knees. Improves balance.', 'cue': 'Foot to ankle, calf or thigh (not the knee). Fix your gaze, breathe steady.', 'image': 'https://res.cloudinary.com/dko1be2jy/image/upload/fl_sanitize/v1676483094/yoga-api/41_veknug.png', 'category': 'standing', 'per_side': True, 'hold': 30},
    'plank': {'label': 'Plank', 'sanskrit': 'Phalakasana', 'description': 'The body is parallel to the earth. The weight of the body is supported by straight arms and active toes. The abdomen is pulled up towards the spine and the pelvis is tucked in. The neck is a natural extension of the…', 'benefits': 'Strengthens the arms, wrists, and spine. Tones the abdomen.', 'cue': 'Shoulders over wrists, body one straight line, core and legs engaged.', 'image': 'https://res.cloudinary.com/dko1be2jy/image/upload/fl_sanitize/v1676483088/yoga-api/26_mxkzlo.png', 'category': 'core', 'per_side': False, 'hold': 30},
    'sphinx': {'label': 'Sphinx', 'sanskrit': 'Salamba Bhujangasana', 'description': 'From a prone position with the pelvic bowl is firmly contracted interiorly towards the center line of the body while the pubis is tucked under. The legs are extended back and the tops of the feet are flat. The palms are…', 'benefits': 'Strengthens the spine. Stretches the chest, the lungs, the shoulders and the abdomen. Stimulates the abdominal organs. Opens the heart and the lungs.', 'cue': 'Forearms down, elbows under shoulders, lift the chest, soften the shoulders.', 'image': 'https://res.cloudinary.com/dko1be2jy/image/upload/fl_sanitize/v1676483092/yoga-api/35_dytwvz.png', 'category': 'core', 'per_side': False, 'hold': 30},
    'up_dog': {'label': 'Upward-Facing Dog', 'sanskrit': 'Urdhva Mukha Svsnssana', 'description': 'The body is in a prone position parallel to the earth. The weight of the body is supported equally by the straight arms and the tops of the feet which press firmly into the earth. The shoulders are rotated back and…', 'benefits': 'Improves posture. Strengthens the spine, arms, and wrists. Stretches the chest, lungs, shoulders, and abdomen. Firms the buttocks. Stimulates abdominal organs.…', 'cue': 'Tops of the feet down, thighs lifted, chest open, shoulders away from ears.', 'image': 'https://res.cloudinary.com/dko1be2jy/image/upload/fl_sanitize/v1676483096/yoga-api/43_m3nxjk.png', 'category': 'core', 'per_side': False, 'hold': 20},
    'bridge': {'label': 'Bridge', 'sanskrit': 'Setu Bandha Sarvangasana', 'description': 'From a supine position, on your back, the hips are pressed up with the heels of the feet rooted into the earth close to the sits bones. The toes are actively lifted and the pelvis tucked. The thighs are parallel to the…', 'benefits': 'Stretches the chest, neck, and spine. Stimulates abdominal organs, lungs, and thyroids. Rejuvenates tired legs. Improves digestion. Helps relieve the symptoms…', 'cue': 'Feet hip-width, press into the feet, lift the hips, roll the shoulders under.', 'image': 'https://res.cloudinary.com/dko1be2jy/image/upload/fl_sanitize/v1676483074/yoga-api/4_qq6nxw.png', 'category': 'core', 'per_side': False, 'hold': 30},
    'boat': {'label': 'Boat', 'sanskrit': 'Navasana', 'description': 'From a seated position the feet are lifted up so that the thighs are angled about 45-50 degrees relative to the earth. The tailbone is lengthened into the earth and the pubis pulls toward the navel. The shoulder blades…', 'benefits': 'Strengthens the abdomen, hip flexors, and spine. Stimulates the kidneys, thyroid and prostate glands, and intestines. Helps relieve stress. Improves digestion.', 'cue': 'Lift the chest, draw the lower belly in, shins parallel to the floor if you can.', 'image': 'https://res.cloudinary.com/dko1be2jy/image/upload/fl_sanitize/v1676483071/yoga-api/1_txmirf.png', 'category': 'core', 'per_side': False, 'hold': 20},
    'butterfly': {'label': 'Butterfly', 'sanskrit': 'Baddha Konasana', 'description': 'In sitting position, bend both knees and drop the knees to each side, opening the hips. Bring the soles of the feet together and bring the heels as close to the groin as possible, keeping the knees close to the ground.…', 'benefits': 'Opens the hips and groins. Stretches the shoulders, rib cage and back. Stimulates the abdominal organs, lungs and heart.', 'cue': 'Soles together, let the knees fall open, sit tall then fold gently forward.', 'image': 'https://res.cloudinary.com/dko1be2jy/image/upload/fl_sanitize/v1676483074/yoga-api/5_i64gif.png', 'category': 'hip', 'per_side': False, 'hold': 40},
    'seated_fold': {'label': 'Seated Forward Bend', 'sanskrit': 'Paschimottanasana', 'description': 'From a seated position with the sits bones rooted into the earth the legs extend forward to the degree that the chest and thighs can stay connected. The fingers wrap around the toes. The upper torso folds forward at the…', 'benefits': 'Calms the brain and helps relieve stress and mild depression. Stretches the spine, shoulders and hamstrings. Stimulates the liver, kidneys, ovaries and uterus.…', 'cue': 'Legs long, hinge from the hips over the legs, keep the spine long, breathe.', 'image': 'https://res.cloudinary.com/dko1be2jy/image/upload/fl_sanitize/v1676483091/yoga-api/30_gumpl3.png', 'category': 'hip', 'per_side': False, 'hold': 40},
    'pigeon': {'label': 'Pigeon', 'sanskrit': 'Supta Kapotasana', 'description': 'Lie on the back in supine position. Bend the knees, heels close to SI bones and cross one ankle over the opposite knee. Thread the hands or reach through between the thighs. Lift the foot off the floor and hold the bent…', 'benefits': 'Stretches the hamstrings and quads. If the elbow is used to push the thigh, it opens the hips as well.', 'cue': 'Front shin forward, back leg long, square the hips, fold over the front leg.', 'image': 'https://res.cloudinary.com/dko1be2jy/image/upload/fl_sanitize/v1676483088/yoga-api/24_ulgsjo.png', 'category': 'hip', 'per_side': True, 'hold': 40},
    'twist': {'label': 'Half Lord of the Fishes', 'sanskrit': 'Ardha Matsyendrasana', 'description': 'Begin in a seated position. Bend one knee so the sole of your foot is close to the opposite inner thigh. Bend your opposite knee in, foot on the floor, heel to the outside of your bent thigh. Extend your arm (same side…', 'benefits': 'Stretches the shoulders, the chest, the thighs, the groins, and the abdomen. Strengthens the legs and the ankles. Improves balance.', 'cue': 'Sit tall, cross one knee, twist toward it on the exhale, lengthen on the inhale.', 'image': 'https://res.cloudinary.com/dko1be2jy/image/upload/fl_sanitize/v1676483091/yoga-api/32_hafoa0.png', 'category': 'cooldown', 'per_side': True, 'hold': 30},
    'garland': {'label': 'Garland Pose', 'sanskrit': 'Malasana', 'description': 'From a squatting position the feet are as close together as possible (keep your heels on the floor if you can; otherwise, support them on a folded mat). The thighs are slightly wider than the torso. The torso is leaning…', 'benefits': 'Stretches the ankles, groins and back torso. Tones the belly.', 'cue': 'Deep squat, heels down if you can, elbows press the knees open, chest lifted.', 'image': 'https://res.cloudinary.com/dko1be2jy/image/upload/fl_sanitize/v1676483093/yoga-api/37_moh7ii.png', 'category': 'hip', 'per_side': False, 'hold': 30},
    'corpse': {'label': 'Corpse', 'sanskrit': 'Sivasana', 'description': 'The body rests on the earth in a supine position with the arms resting by the side body. The palms are relaxed and open toward the sky. The shoulder blades are pulled back, down and rolled under comfortably, resting…', 'benefits': 'Calms the brain and helps relieve stress and mild depression. Relaxes the body. Reduces headache, fatigue, and insomnia. Helps to lower blood pressure.', 'cue': 'Lie flat, arms relaxed, eyes closed. Let everything go and just breathe.', 'image': 'https://res.cloudinary.com/dko1be2jy/image/upload/fl_sanitize/v1676483078/yoga-api/11_dczyrp.png', 'category': 'cooldown', 'per_side': False, 'hold': 75},
}
